feat: apply Jira custom data

diff --git a/.github/workflows/create_release.yaml b/.github/workflows/create_release.yaml
--- a/.github/workflows/create_release.yaml
+++ b/.github/workflows/create_release.yaml
@@ -26,6 +26,7 @@ jobs:
     outputs:
       repo: ${{ steps.set_env.outputs.repo }}
       release_branch: ${{ steps.set_env.outputs.release_branch }}
+      release_env: ${{ steps.set_env.outputs.release_env }}
     name: Initial Setting
     runs-on: ubuntu-latest
     steps:
@@ -45,13 +46,22 @@ jobs:
             repo=`jq --compact-output --null-input '$ARGS.positional' --args -- "${repo[@]}"`
             release_branch=main
           fi
+
+          release_env="${{ inputs.release_env }}"
           
           echo "Repository  : $REPO\nBranch      : $REPO1"
           echo "repo=$repo" >> $GITHUB_OUTPUT
           echo "release_branch=$release_branch" >> $GITHUB_OUTPUT
+          echo "release_env=$release_env" >> $GITHUB_OUTPUT
+
+      - name: Fail if environment is unknown
+        if: ${{ steps.set_env.outputs.release_env != 'QA' && steps.set_env.outputs.release_env != 'PROD' && !contains(steps.set_env.outputs.release_env, 'hotfix/') }}
+        run: |
+          echo "Environment is not QA, PROD, or HOTFIX. Failing the workflow."
+          exit 1
           
-  create-release:
-    name: Create tag for new image
+  create-release-and-trigger-deployment:
+    name: Create tag for new image and trigger deployment
     needs: [initial_setting]
     environment: ${{ github.ref_name }}
     runs-on: ubuntu-latest
@@ -62,10 +72,16 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0
           repository: cloud-development-team/${{ matrix.repo }}
           ref: refs/heads/${{ needs.initial_setting.outputs.release_branch }}
           token: ${{ secrets.AUTOMATION_GH_MANAGEPACKAGE_TOKEN }}
+
+      - name: Trigger Project Workflow
+        run: |
+          curl -X POST -H "Accept: application/vnd.github.v3+json" \
+          -H "Authorization: token ${{ secrets.AUTOMATION_GH_MANAGEPACKAGE_TOKEN }}" \
+          https://api.github.com/repos/cloud-development-team/${{ matrix.repo }}/dispatches \
+          -d '{"event_type":"jira_release","client_payload":{"release_env":"${{ needs.initial_setting.outputs.release_env }}"}}'
 
       - name: Create Github Release
         uses: actions/create-release@v1
