feat: add dmpro lambda cicd-prod

diff --git a/.github/workflows/deploy-dmpro.yaml b/.github/workflows/deploy-dmpro.yaml
--- a/.github/workflows/deploy-dmpro.yaml
+++ b/.github/workflows/deploy-dmpro.yaml
@@ -84,43 +84,43 @@ jobs:
           ref: refs/heads/main
           token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
           
-      # - name: Update version.json information
-      #   uses: mikefarah/yq@v4.34.2
-      #   with:
-      #     cmd: |
-      #       yq -i '.["JiraReleaseVersion"].["MainVersion"] = "${{ inputs.release_version }}"' qa_version.json     
-      #       yq -i '.["JiraReleaseVersion"].["SWVersion"] = "${{ inputs.dm_sw_ver }}"' qa_version.json     
+      - name: Update version.json information
+        uses: mikefarah/yq@v4.34.2
+        with:
+          cmd: |
+            yq -i '.["JiraReleaseVersion"].["MainVersion"] = "${{ inputs.release_version }}"' qa_version.json     
+            yq -i '.["JiraReleaseVersion"].["SWVersion"] = "${{ inputs.dm_sw_ver }}"' qa_version.json     
 
-      # - name: Get Time
-      #   id: time
-      #   uses: nanzm/get-time-action@master
-      #   with:
-      #     timeZone: UTC-9
-      #     format: 'YYYY-MM-DD HH:mm:ss'
+      - name: Get Time
+        id: time
+        uses: nanzm/get-time-action@master
+        with:
+          timeZone: UTC-9
+          format: 'YYYY-MM-DD HH:mm:ss'
 
-      # - name: Update Release date to version.json information
-      #   uses: mikefarah/yq@v4.34.2
-      #   with:
-      #     cmd: |
-      #       yq -i '.["JiraReleaseVersion"].["ReleaseDate"] = "${{ steps.time.outputs.time }}"' qa_version.json
+      - name: Update Release date to version.json information
+        uses: mikefarah/yq@v4.34.2
+        with:
+          cmd: |
+            yq -i '.["JiraReleaseVersion"].["ReleaseDate"] = "${{ steps.time.outputs.time }}"' qa_version.json
 
-      # - name: Install yq
-      #   run: |
-      #     wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O /usr/local/bin/yq
-      #     chmod +x /usr/local/bin/yq
+      - name: Install yq
+        run: |
+          wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O /usr/local/bin/yq
+          chmod +x /usr/local/bin/yq
 
-      # - name: Deploy
-      #   run: |
-      #     while IFS= read -r line; do
-      #       if [[ "${line:0:1}" != " " ]]; then
-      #         service_name=$(echo "$line" | awk -F':' '{print $1}')
-      #       elif [[ $line == *"image-tag"* ]]; then
-      #         image_tag=$(echo "$line" | awk -F': "' '{print $2}' | awk -F'"' '{print $1}')
-      #         yq -i '
-      #           .image.tag = "'$image_tag'"
-      #         ' ./$service_name/env/qa.yaml || true
-      #       fi
-      #     done < qa_version.yaml
+      - name: Deploy
+        run: |
+          while IFS= read -r line; do
+            if [[ "${line:0:1}" != " " ]]; then
+              service_name=$(echo "$line" | awk -F':' '{print $1}')
+            elif [[ $line == *"image-tag"* ]]; then
+              image_tag=$(echo "$line" | awk -F': "' '{print $2}' | awk -F'"' '{print $1}')
+              yq -i '
+                .image.tag = "'$image_tag'"
+              ' ./$service_name/env/qa.yaml || true
+            fi
+          done < qa_version.yaml
 
       - name: Copy the qa_version.yaml file to prod_version.yaml file.
         run: |
@@ -138,54 +138,54 @@ jobs:
           git push origin main
         continue-on-error: true
 
-      # - name: Configure AWS credentials
-      #   uses: aws-actions/configure-aws-credentials@v4
-      #   with:
-      #     role-to-assume: arn:aws:iam::619268642609:role/HVC-admin-automation
-      #     role-session-name: GitHub-Actions-Assume
-      #     aws-region: us-east-1
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::619268642609:role/HVC-admin-automation
+          role-session-name: GitHub-Actions-Assume
+          aws-region: us-east-1
       
-      # # Static file upload
-      # - name: Static File Update - QA
-      #   run: |
-      #     export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
-      #     $(aws sts assume-role \
-      #     --role-arn arn:aws:iam::${{ inputs.qa_aws_account }}:role/AWSControlTowerExecution \
-      #     --role-session-name GitHubPipeline \
-      #     --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
-      #     --output text))
+      # Static file upload
+      - name: Static File Update - QA
+        run: |
+          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
+          $(aws sts assume-role \
+          --role-arn arn:aws:iam::${{ inputs.qa_aws_account }}:role/AWSControlTowerExecution \
+          --role-session-name GitHubPipeline \
+          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
+          --output text))
 
-      #     if ${{ inputs.release_env == 'QA' }} ; then
-      #       if aws s3 ls s3://${{ inputs.qa_fe_bucket }}/major/pre-out/ ; then
-      #         echo "S3 path s3://${{ inputs.qa_fe_bucket }}/major/pre-out exist. "
-      #         # Check who am I
-      #         aws sts get-caller-identity
+          if ${{ inputs.release_env == 'QA' }} ; then
+            if aws s3 ls s3://${{ inputs.qa_fe_bucket }}/major/pre-out/ ; then
+              echo "S3 path s3://${{ inputs.qa_fe_bucket }}/major/pre-out exist. "
+              # Check who am I
+              aws sts get-caller-identity
 
-      #         # Sync S3 Bucket
-      #         aws s3 sync s3://${{ inputs.qa_fe_bucket }}/major/pre-out s3://${{ inputs.qa_fe_bucket }}/major/out --delete
-      #         aws s3 rm s3://${{ inputs.qa_fe_bucket }}/major/pre-out --recursive
+              # Sync S3 Bucket
+              aws s3 sync s3://${{ inputs.qa_fe_bucket }}/major/pre-out s3://${{ inputs.qa_fe_bucket }}/major/out --delete
+              aws s3 rm s3://${{ inputs.qa_fe_bucket }}/major/pre-out --recursive
 
-      #         # Setting CloudFront
-      #         aws cloudfront create-invalidation --distribution-id "EOTSDFTM2NPH0" --paths "/*"
-      #       else
-      #         echo "S3 path s3://${{ inputs.qa_fe_bucket }}/major/pre-out does not exist. Skipping sync and invalidation."
-      #       fi
-      #     elif ${{ inputs.release_env == 'QAMINOR' }} ; then
-      #       if aws s3 ls s3://${{ inputs.qa_fe_bucket }}/minor/pre-out/ ; then
-      #         echo "S3 path s3://${{ inputs.qa_fe_bucket }}/minor/pre-out exist. "
-      #         # Check who am I
-      #         aws sts get-caller-identity
+              # Setting CloudFront
+              aws cloudfront create-invalidation --distribution-id "EOTSDFTM2NPH0" --paths "/*"
+            else
+              echo "S3 path s3://${{ inputs.qa_fe_bucket }}/major/pre-out does not exist. Skipping sync and invalidation."
+            fi
+          elif ${{ inputs.release_env == 'QAMINOR' }} ; then
+            if aws s3 ls s3://${{ inputs.qa_fe_bucket }}/minor/pre-out/ ; then
+              echo "S3 path s3://${{ inputs.qa_fe_bucket }}/minor/pre-out exist. "
+              # Check who am I
+              aws sts get-caller-identity
 
-      #         # Sync S3 Bucket
-      #         aws s3 sync s3://${{ inputs.qa_fe_bucket }}/minor/pre-out s3://${{ inputs.qa_fe_bucket }}/minor/out --delete
-      #         aws s3 rm s3://${{ inputs.qa_fe_bucket }}/minor/pre-out --recursive
+              # Sync S3 Bucket
+              aws s3 sync s3://${{ inputs.qa_fe_bucket }}/minor/pre-out s3://${{ inputs.qa_fe_bucket }}/minor/out --delete
+              aws s3 rm s3://${{ inputs.qa_fe_bucket }}/minor/pre-out --recursive
 
-      #         # Setting CloudFront
-      #         aws cloudfront create-invalidation --distribution-id "E391GJR6NFDKFC" --paths "/*"
-      #       else
-      #         echo "S3 path s3://${{ inputs.qa_fe_bucket }}/minor/pre-out does not exist. Skipping sync and invalidation."
-      #       fi
-      #     fi 
+              # Setting CloudFront
+              aws cloudfront create-invalidation --distribution-id "E391GJR6NFDKFC" --paths "/*"
+            else
+              echo "S3 path s3://${{ inputs.qa_fe_bucket }}/minor/pre-out does not exist. Skipping sync and invalidation."
+            fi
+          fi 
 
   #1.0.2 SSR 구성
   hotfix-deploy:
@@ -266,87 +266,87 @@ jobs:
       node_versions: "['20.14.0']"
     secrets: inherit
 
-  # prod-deploy:
-  #   name: DMPro PROD Deploy
-  #   if: ${{ inputs.release_env == 'PROD' || inputs.release_env == 'PRODMINOR' }} 
-  #   environment: main
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #         repository: cloud-development-team/${{ inputs.release_repo }}
-  #         ref: refs/heads/main
-  #         token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
+  prod-deploy:
+    name: DMPro PROD Deploy
+    if: ${{ inputs.release_env == 'PROD' || inputs.release_env == 'PRODMINOR' }} 
+    environment: main
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          repository: cloud-development-team/${{ inputs.release_repo }}
+          ref: refs/heads/main
+          token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
           
-  #     - name: Update version.json information
-  #       uses: mikefarah/yq@v4.34.2
-  #       with:
-  #         cmd: |
-  #           yq -i '.["JiraReleaseVersion"].["MainVersion"] = "${{ inputs.release_version }}"' prod_version.json     
-  #           yq -i '.["JiraReleaseVersion"].["SWVersion"] = "${{ inputs.dm_sw_ver }}"' prod_version.json
+      - name: Update version.json information
+        uses: mikefarah/yq@v4.34.2
+        with:
+          cmd: |
+            yq -i '.["JiraReleaseVersion"].["MainVersion"] = "${{ inputs.release_version }}"' prod_version.json     
+            yq -i '.["JiraReleaseVersion"].["SWVersion"] = "${{ inputs.dm_sw_ver }}"' prod_version.json
 
-  #     - name: Get Time
-  #       id: time
-  #       uses: nanzm/get-time-action@master
-  #       with:
-  #         timeZone: UTC-9
-  #         format: 'YYYY-MM-DD HH:mm:ss'
+      - name: Get Time
+        id: time
+        uses: nanzm/get-time-action@master
+        with:
+          timeZone: UTC-9
+          format: 'YYYY-MM-DD HH:mm:ss'
 
-  #     - name: Update Release date to version.json information
-  #       uses: mikefarah/yq@v4.34.2
-  #       with:
-  #         cmd: |
-  #           yq -i '.["JiraReleaseVersion"].["ReleaseDate"] = "${{ steps.time.outputs.time }}"' prod_version.json
+      - name: Update Release date to version.json information
+        uses: mikefarah/yq@v4.34.2
+        with:
+          cmd: |
+            yq -i '.["JiraReleaseVersion"].["ReleaseDate"] = "${{ steps.time.outputs.time }}"' prod_version.json
 
-  #     - name: Install yq
-  #       run: |
-  #         wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O /usr/local/bin/yq
-  #         chmod +x /usr/local/bin/yq
+      - name: Install yq
+        run: |
+          wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O /usr/local/bin/yq
+          chmod +x /usr/local/bin/yq
 
-  #     - name: Deploy
-  #       run: |
-  #         while IFS= read -r line; do
-  #           if [[ "${line:0:1}" != " " ]]; then
-  #             service_name=$(echo "$line" | awk -F':' '{print $1}')
-  #           elif [[ $line == *"image-tag"* ]]; then
-  #             image_tag=$(echo "$line" | awk -F': "' '{print $2}' | awk -F'"' '{print $1}')
-  #             yq -i '
-  #               .image.tag = "'$image_tag'"
-  #             ' ./$service_name/env/prod.yaml || true
-  #           fi
-  #         done < prod_version.yaml
+      - name: Deploy
+        run: |
+          while IFS= read -r line; do
+            if [[ "${line:0:1}" != " " ]]; then
+              service_name=$(echo "$line" | awk -F':' '{print $1}')
+            elif [[ $line == *"image-tag"* ]]; then
+              image_tag=$(echo "$line" | awk -F': "' '{print $2}' | awk -F'"' '{print $1}')
+              yq -i '
+                .image.tag = "'$image_tag'"
+              ' ./$service_name/env/prod.yaml || true
+            fi
+          done < prod_version.yaml
 
-  #     - name: Commit changes
-  #       run: |
-  #         git config user.name "GitHub Actions Bot" && \
-  #         git config user.email "<>" && \
-  #         git add --all
-  #         git commit -m "cd: deploy dmpro prod version ${{ inputs.release_version }}" && \
-  #         git push origin main
-  #       continue-on-error: true
+      - name: Commit changes
+        run: |
+          git config user.name "GitHub Actions Bot" && \
+          git config user.email "<>" && \
+          git add --all
+          git commit -m "cd: deploy dmpro prod version ${{ inputs.release_version }}" && \
+          git push origin main
+        continue-on-error: true
       
-  #     # Login To HVC_Admin_Automation for Deploy
-  #     - name: Configure AWS credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         role-to-assume: arn:aws:iam::619268642609:role/HVC-admin-automation
-  #         role-session-name: GitHub-Actions-Assume
-  #         aws-region: us-east-1
+      # Login To HVC_Admin_Automation for Deploy
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::619268642609:role/HVC-admin-automation
+          role-session-name: GitHub-Actions-Assume
+          aws-region: us-east-1
 
-  #     # Static file upload
-  #     - name: Static File Update - PROD
-  #       run: |
-  #         export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
-  #         $(aws sts assume-role \
-  #         --role-arn arn:aws:iam::${{ inputs.prod_aws_account }}:role/AWSControlTowerExecution \
-  #         --role-session-name GitHubPipeline \
-  #         --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
-  #         --output text))
+      # Static file upload
+      - name: Static File Update - PROD
+        run: |
+          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
+          $(aws sts assume-role \
+          --role-arn arn:aws:iam::${{ inputs.prod_aws_account }}:role/AWSControlTowerExecution \
+          --role-session-name GitHubPipeline \
+          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
+          --output text))
 
-  #         aws s3 sync s3://${{ inputs.qa_fe_bucket }}/${{ inputs.dm_sw_ver }}/out ./out
-  #         aws s3 sync ./out s3://${{ inputs.prod_fe_bucket }}/out --delete
+          aws s3 sync s3://${{ inputs.qa_fe_bucket }}/${{ inputs.dm_sw_ver }}/out ./out
+          aws s3 sync ./out s3://${{ inputs.prod_fe_bucket }}/out --delete
 
-  #         # Setting CloudFront
-  #         aws cloudfront create-invalidation --distribution-id ${{ inputs.prod_cf_distribution_id }} --paths "/*"
+          # Setting CloudFront
+          aws cloudfront create-invalidation --distribution-id ${{ inputs.prod_cf_distribution_id }} --paths "/*"
